### ISSUE TITLE
Client-side updating of relationship filters

### ISSUE THREAD

**Issue by JedWatson** [keystonejs/keystone-classic#10]
Relationship fields with filters that depend on other values become unavailable in the UI when (a) no value is set, or (b) the value is changed, until the item is saved because the filter values are resolved server-side based on the saved item data.

Client-side submission of the current value of the dependencies will make the workflow faster.

This should potentially include consolidation of the select2 implementation for relationship fields.

**Comment by romecode** [comment]
I am trying to implement what sounds like the process described in this thread, and if I am interpreting it correctly this is what should happen:

A field is dependent on another:
categories: {type: Types.Relationship, ref: 'Categories', many: true,filters:{category_types:":type"}}
where :type is that same models field
and if "type" is changed "categories" should update client-side

The functionality does happen in this matter, however, i have to fidget with the "categories" field to get it to trigger the update... in other words the options stay the same until I select one and then delete it; only then do I notice a network request and a refresh of the options.

Any ideas?

P.S. the type field is another relationship field:
type: {type: Types.Relationship, ref: 'Types',initial:true}

Thanks in advance
