### ISSUE TITLE
New field type: array

### ISSUE THREAD

**Issue by JedWatson** [keystonejs/keystone-classic#13]
Add an `array` field type that stores a simple list of `String`, `Number` or `Date` values.

**Comment by Pylipala** [comment]
Can I use array of custom inline object?
For example, I have an order model, which contains many order details. I want the order header and its details to be in the same mongodb document. Is it possible in keystonejs?

**Comment by QualityWorksCG** [comment]
Would love the ability to have an array of Type.Select

**Comment by morenoh149** [comment]
@Pylipala @QualityWorksCG open up a new issue if you think its a good new feature

**Comment by VinayaSathyanarayana** [comment]
Where can one find documentation of TextArray and NumberArray?

**Comment by morenoh149** [comment]
@JedWatson https://github.com/keystonejs/keystone/issues/1021 do you need to cut a new site update?

**Comment by dsmurl** [comment]
Would be nice to have for adding varying number of images to an article, recipe, or other list type item.

That is to say, an array of type Image or something.
