### ISSUE TITLE
Disable showing List in Admin UI

### ISSUE THREAD

**Issue by brankosekulic** [keystonejs/keystone-classic#166]
I would like to create some List which is not displayed in Admin Panel.
Is there some already available option for that ? (I thought passing additional param to register method would be good)

**Comment by monkeycycle** [comment]
Does this actually work under 4.0.0-beta.5 ? I have it set but the list still appears in the Admin UI. Wondering if it's me or a missing feature.

**Comment by VinayaSathyanarayana** [comment]
One gets an error if the User List is hidden - Is that intentional?

**Comment by cbrian** [comment]
Same for me.

**Comment by ArulJothy-J** [comment]
> I added this as an option to the list constructor:
> 
> ```js
> var MyList = new keystone.List({
>     hidden: true
> });
> ```
> 
> I realised you could easily set it to be visible or hidden in production mode by doing this:
> 
> ```js
> var MyList = new keystone.List({
>     hidden: (keystone.get('env') == 'production')
> });
> ```
> 
> Will hit npm with v0.2.3 soon.

it's not working in 4.0.0, still, it appears in Admin UI

**Comment by GreenMonkeySaveEarth** [comment]
I am on lates V4.2.1. It's not working. 
Throw the following error in the console. 
```
throw new Error('Invalid Keystone Option (nav): list ' + i + ' is hidden.\n');
```
Any update on this field.
