### ISSUE TITLE
React Editors

### ISSUE THREAD

**Issue by jossmac** [keystonejs/keystone-classic#1892]
Putting this here for consideration. The only thing stopping us from removing jQuery from KeystoneJS is the editors.

WYSIWYG candidates:
- https://zenoamaro.github.io/react-quill
- http://alloyeditor.com/demo

Markdown candidates:
- http://jedwatson.github.io/react-md-editor
- http://jrm2k6.github.io/react-markdown-editor
- http://oscargodson.github.io/EpicEditor
- https://tibastral.github.io/markdownify
- https://jonschlinkert.github.io/remarkable/demo (parser only)

---

EDIT: Please comment if I've missed a quality React.js based WYSIWYG and Markdown editor

**Comment by christroutner** [comment]
Is removal of jQuery seriously being considered? Even if KeystoneJS doesn't require it, most people will want it for their own customization.

**Comment by ignlg** [comment]
jQuery + React.js is a bad mix. You shouldn't manipulate the DOM directly, React uses the DOM as a reflection of the application's state. If you want to change the DOM, change the state.

**Comment by lojack** [comment]
@christroutner If users need it for their customization then there isn't anything stopping them from including their own version somewhere, but if it isn't being used by Keystone then it makes sense to remove it.

**Comment by jossmac** [comment]
@christroutner have a quick read of @JedWatson's outline in #503 - one of the driving factors for rebuilding the Admin UI in React.js is to make customisation more accessible

**Comment by morenoh149** [comment]
markdown
http://oscargodson.github.io/EpicEditor/
https://tibastral.github.io/markdownify/

**Comment by ericelliott** [comment]
:+1: 

I'm a big fan of Markdown, but I'm also a big fan of Medium-style editing for the non-technical users.

Is there a best of both worlds?

**Comment by tnottu** [comment]
[Woofmark](https://github.com/bevacqua/woofmark) seems a bit like "best of both worlds" as it has Markdown, WYSIWYG and HTML modes. It could be also used in combination with [Horsey](https://github.com/bevacqua/horsey) to create "autocomplete-as-you-type" feature, [demo here](http://codepen.io/bevacqua/pen/bdxajE).

**Comment by morenoh149** [comment]
http://facebook.github.io/draft-js/ we use this one right ;)

**Comment by mxstbr** [comment]
Has this happened yet? http://facebook.github.io/draft-js/ in combination with https://www.draft-js-plugins.com is amazing! (I might be biased though, helped build DraftJS Plugins.. :grin: )

**Comment by kadosh1000** [comment]
@jossmac Why not using TinyMCE with react,
I think that TinyMCE is the most mature wysiwyg editor today and have the largest plugin collection out there. There is a way to integrate it with react : 

https://www.tinymce.com/docs/integrations/react/

This way the users migrating from 0.3.x to 0.4.x won't need to change their configuration.
The migration progress should be as nice and easy as possible

**Comment by jossmac** [comment]
@kadosh1000 I hear you, but not to worry `0.4.0` will likely ship with TinyMCE in its current state.

Maturity is great and TinyMCE has served us well, but we need to move forward; Draft.js gives us flexibility to do that.

On a more general note, react wrappers around existing libraries tend to be difficult to work with, at least that's what I've found in a few cases.

**Comment by wmertens** [comment]
draft.js does look amazing, but there's also Slate which sounds like it knows what it is doing https://github.com/ianstormtaylor/slate/blob/master/Readme.md#why

**Comment by mashaal** [comment]
Hey everyone, I have draft-js working in my keystone. It's using the [rich text example in the draft-js official repo](https://github.com/facebook/draft-js/blob/master/examples/draft-0-10-0/rich/rich.html). I tried to make it as backwards compatible with the existing TinyMCE editors (it will read/format the same data between the two, but the draft-js functionality is limited compared to TinyMCE at the moment).

It's not pretty in terms of styling, but is way less buggy than the current TinyMCE editors. (They don't work properly in the [nested-lists branch](https://github.com/keystonejs/keystone/pull/3282).)

Would like help cleaning up and maybe then opening a pull request?

![draft-js](https://user-images.githubusercontent.com/6100364/28853468-11448fbe-7774-11e7-8385-6151de7e6506.gif)

**Comment by l3wi** [comment]
@mashaal 10/10 on the demo gif

**Comment by wmertens** [comment]
There's also https://github.com/ianstormtaylor/slate#why

> Here's how Slate compares to some of the existing editors out there:

   -

   Draft.js <https://facebook.github.io/draft-js/> — Slate borrowed a few
   concepts from Draft.js, namely its event system, its use of Immutable.js
   and React, and its goal of being a "framework" for creating editors. It
   also borrowed its plugin-centric design from the Draft.js Plugins
   <https://github.com/draft-js-plugins/draft-js-plugins> project. But the
   issues I ran into while using Draft.js were: that lots of the logic around
   the schema is hardcoded in "core" and difficult to customize, that the
   transform API is complex to use and not suited to collaborative editing in
   the future, that serialization isn't considered by the core library in a
   nice way, that the flat document model made certain behaviors impossible,
   and that lots of the API feels very heavy to work with.

Of course, if all Keystone is interested in is a rich text editor without
worrying about integration with Keystone proper, it may be better to go
with the biggest, so Draft.
