### ISSUE TITLE
Remember URL when bouncing to signin

### ISSUE THREAD

**Issue by JedWatson** [keystonejs/keystone-classic#206]
If you need to sign in to access the Admin UI, Keystone will forget which URL you were trying to go to.

We should include a parameter for the signin page that bounces you back to a specific URL after you successfully sign in.

**Comment by acontreras89** [comment]
Hey @JedWatson, can you please point to the commit or sources where this has been added?

**Comment by JedWatson** [comment]
@acontreras89 the parameter is passed by the session middleware:

https://github.com/keystonejs/keystone/blob/master/lib/session.js#L210-L216

Bouncing was implemented in the signin route for 0.3, has now been moved into the react view in 0.4

**Comment by acontreras89** [comment]
thanks @JedWatson!
I had already found it diving a bit into Keystone's source, sorry I didn't write here with my findings.

**Comment by JedWatson** [comment]
@acontreras89 cool, no worries - sorry I took so long to reply! huge backlog :)
