### ISSUE TITLE
Set List collection name

### ISSUE THREAD

**Issue by bufke** [keystonejs/keystone-classic#292]
It would be useful for when working with existing mongo schemas. For example if I have a mongo schema named 'foo' I could define this as a list. However Keystone will set the collection name as 'foos'.

**Comment by chasms** [comment]
@JedWatson in the documentation the `schema` option is notated as type `String` (both [HERE](http://keystonejs.com/docs/database/#lists-options) and [HERE](http://keystonejs.netlify.com/api/list/options/); this should probably be set to `Object`, and it would be nice to show a little example too

**Comment by stennie** [comment]
@chasms New issue reported against current version of Keystone is definitely preferable to re-opening old issues. If you reference the prior issue by number (eg #292) when creating a new report, GitHub will automatically link the issues as related.

Thanks,
Stennie
