### ISSUE TITLE
Generate error on required field not marked initial and lacking default value

### ISSUE THREAD

**Issue by webteckie** [keystonejs/keystone-classic#300]
From @JedWatson  in Keystone Google Group topic (https://groups.google.com/forum/#!topic/keystonejs/sfK1-4IosKA):

If we're going to do this, I'd prefer Keystone to throw a config error if a field is required but not initial, rather than making 'required' a synonym for 'initial'.

The reason it's not in there at the moment is there are valid reasons why you might have a required field that's not in the initial form (e.g. populated / defaulted by some other process unknown to the field itself).

Maybe a good balance is to throw an error (same technique as when you mark fields as initial when their type doesn't support it) IF
required: true
initial: undefined
default: undefined
That way if the field's got a default value, or initial is false, Keystone knows you know what you're doing.

Would love a PR implementing this if anyone gets the chance.

**Comment by tortilaman** [comment]
As it currently exists, it seems that having a field required and not initial isn't allowed. In my particular instance, I need all the fields to be required, but they don't all fit on the initial screen, so I wanted them to be on the subsequent editing screen.

Is there a way to make this work so I can require fields with initial set to false? I've tried defaulting the number type fields to 0, but that doesn't seem to work.

**Comment by Noviny** [comment]
@tortilaman It sounds like you've run into a different bug. This should be fine if it is required and default, however my guess is default of '0' is at some point being checked for truthiness, which '0' will fail.

Just to verify, can you confirm that this works fine for other fields, and for a number field that does not default to 0?

**Comment by tarun4all** [comment]
if you turn **nocreate** true then it will always show this error and initial needed.
