### ISSUE TITLE
List view breaks on invalid sort, and when `_id` is provided as the sort

### ISSUE THREAD

**Issue by jossmac** [keystonejs/keystone-classic#3127]
See https://github.com/keystonejs/keystone-test-project @ http://localhost:3000/keystone/autocreates

Warning: `Invalid Sort specified: _id`

**Comment by mxstbr** [comment]
Can replicate, but no idea how to fix this. Over to you @JedWatson!

**Comment by tmvanetten** [comment]
If you `map: { name: 'SomeField' },` it does not throw the error for me.
