### ISSUE TITLE
Explorer Fields

### ISSUE THREAD

**Issue by jossmac** [keystonejs/keystone-classic#3145]
- [x] Boolean
- [x] Cloudinaryimage
- [x] Cloudinaryimages
- [x] Code
- [x] Color
- [x] Date
- [x] Datearray
- [x] Datetime
- [x] Email
- [x] ~~Embedly~~
- [ ] File
- [x] Geopoint
- [x] Html
- [x] Key
- [x] Location
- [x] Markdown
- [x] Money
- [x] Name
- [x] Number
- [x] Numberarray
- [x] Password
- [x] Relationship (will require stub data)
- [x] Select
- [x] Text
- [x] Textarea
- [x] Textarray
- [x] Url

**Comment by jossmac** [comment]
Handing over to @JedWatson for `File` and `Relationship` fields

**Comment by mxstbr** [comment]
:tada:

**Comment by mxstbr** [comment]
:tada:
