### ISSUE TITLE
GA Tracking issues

### ISSUE THREAD

**Issue by jamlen** [keystonejs/keystone-classic#327]
So I've added my Google Analytics tracking script into my `base.jade` layout, but when I have gone into GA, I am also seeing the Admin UI being tracked! How can I simply prevent this? I assumed that it was using it's own template and therefore wouldn't pick up the one from the main site.

**Comment by joshghent** [comment]
Apologies for commenting on a closed issue but what kind of thing should be going in the GA_SITE_PROPERTY and SITE_DOMAIN?

I'm guessing site domain would be "http://example.com" but I'm not sure about property. Could you shed some light on this?
