### ISSUE TITLE
Do we need support for IE8 in the Admin UI?

### ISSUE THREAD

**Issue by JedWatson** [keystonejs/keystone-classic#339]
We're considering how best to enhance the Admin UI and open it up to customisation.

At the moment, it is intended to be compatible with IE8+

This compatibility isn't extensively tested, but specifically no decisions that would block compatibility have been made yet (e.g. still using jQuery 1.x, including Shims, etc.)

IE8 **does** hold us back quite a bit though; we can't play with new tools like [Polymer](http://www.polymer-project.org) or [tether](http://tether.io) without explicitly breaking compatibility with IE8 (and possibly IE9).

So I thought the best option is to gauge community feedback on how much we should constrain our enthusiasm for these projects in order to support older browsers.

At some point in the project (probably within a year) we'll switch to evergreen browser support only for the Admin UI, and start taking better advantage of the great modern platforms and features that are becoming more and more available.

In the meantime however we have a choice; either embrace this future now and potentially lock-out some of our audience, or continue to user simpler (more old-school) techniques for the Admin UI and make some compromises in the name of compatibility.

Whenever we move to drop support for older browsers, we'll leave the current version branch maintained so that people who _really need_ the compatibility still have a version of Keystone to use, so I guess the question is really how far do we go before we do that.

Please let us know what you think, including if there are any major projects out there for whom dropping IE8 support would be a real issue.

Thanks!
Jed.

**Comment by jjhesk** [comment]
I am totally pro polymer. I think this era is coming very soon and people will possible forget IE8 and the old days. Polymer will bring the whole new ERA to web app world eventually. Sorry for this bold statement.

**Comment by aaronpowell** [comment]
I think you'll find @JedWatson had moved off polymer and is all up in React now :stuck_out_tongue:

**Comment by jjhesk** [comment]
Finally I have caught up with React and it seems to give a promising performance on UI updates mechanism. On the other hand, polymer starts with the shadow dom which does things on the lower level and it will handled by the google chrome built-in components such as rendering calculations. I think polymer will be adopted by keystone in the long run. React on the other hand are built by the instagram and facebook people and have developed a library to solve the current issue browser dom updating issues. I think it will be notified and be adopted into the next gen browser. 

In my opinion, the xml declaration style on shadow dom gives an easy access on language understanding and writing style while react relies on JSX to declare easy component controls.
