### ISSUE TITLE
Deploying Keystone on OpenShift

### ISSUE THREAD

**Issue by perryao** [keystonejs/keystone-classic#365]
Sorry if this isn't the appropriate place to ask this, but has anyone successfully deployed keystone to OpenShift?(https://www.openshift.com). I haven't had any luck, but I'm assuming I just need to know how to configure things properly. Thanks

**Comment by niravshah** [comment]
Hi,

Has anyone encountered the below on OpenShift or any pointers on how to solve it?

Thanks!
Nirav

remote: Traceback (most recent call last):                                                                                                                                                                          
remote:   File "/opt/rh/v8314/root/usr/bin/gyp", line 15, in <module>                                                                                                                                               
remote:     import gyp                                                                                                                                                                                              
remote: ImportError: No module named gyp                                                                                                                                                                            
remote: gyp ERR! configure error                                                                                                                                                                                    
remote: gyp ERR! stack Error: `gyp` failed with exit code: 1                                                                                                                                                        
remote: gyp ERR! stack     at ChildProcess.onCpExit (/opt/rh/nodejs010/root/usr/lib/node_modules/node-gyp/lib/configure.js:343:16)                                                                                  
remote: gyp ERR! stack     at ChildProcess.emit (events.js:98:17)                                                                                                                                                   
remote: gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)                                                                                                                         
remote: gyp ERR! System Linux 2.6.32-504.16.2.el6.x86_64                                                                                                                                                            
remote: gyp ERR! command "node" "/opt/rh/nodejs010/root/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"                                                                                   
remote: gyp ERR! cwd /var/lib/openshift/559fa9944382ec4cf1000106/app-root/runtime/repo/node_modules/keystone/node_modules/keystone-utils/node_modules/limax/node_modules/cld                                        
remote: gyp ERR! node -v v0.10.35                                                                                                                                                                                   
remote: gyp ERR! node-gyp -v v1.0.2                                                                                                                                                                                 
remote: gyp ERR! not ok                                                                                                                                                                                             
remote:                                                                                                                                                                                                             
remote: npm info cld@2.4.3 Failed to exec install script                                                                                                                                                            
remote: npm ERR! EEXIST, open '/var/lib/openshift/559fa9944382ec4cf1000106/.npm/0fe9cfe4-6-npm-mime-db-1-14-0-package-tgz.lock'                                                                                     
remote: File exists: /var/lib/openshift/559fa9944382ec4cf1000106/.npm/0fe9cfe4-6-npm-mime-db-1-14-0-package-tgz.lock                                                                                                
remote: Move it away, and try again.                                                                                                                                                                                
remote: npm ERR! System Linux 2.6.32-504.16.2.el6.x86_64                                                                                                                                                            
remote: npm ERR! command "node" "/opt/rh/nodejs010/root/usr/bin/npm" "install" "-d"                                                                                                                                 
remote: npm ERR! cwd /var/lib/openshift/559fa9944382ec4cf1000106/app-root/runtime/repo                                                                                                                              
remote: npm ERR! node -v v0.10.35                                                                                                                                                                                   
remote: npm ERR! npm -v 1.4.28                                                                                                                                                                                      
remote: npm ERR! path /var/lib/openshift/559fa9944382ec4cf1000106/.npm/0fe9cfe4-6-npm-mime-db-1-14-0-package-tgz.lock                                                                                               
remote: npm ERR! code EEXIST                                                                                                                                                                                        
remote: npm ERR! errno 47

**Comment by JedWatson** [comment]
@sanatpanda3 I recommend posting to the google group or gitter chat for help, we use these issues to track development (not support)
