### ISSUE TITLE
Unclear how to force Cloudinary requests over HTTPS

### ISSUE THREAD

**Issue by maackle** [keystonejs/keystone-classic#373]
I configured my NGINX server to use SSL directly without going through the Keystone SSL server. Everything works fine, except that all Cloudinary requests are over HTTP, which is raining on my parade. I don't see any straightforward way to let Keystone know that I am indeed attempting to use SSL and that it should use https:// prefixes for Cloudinary URLs, and I don't see anything in the documentation about this. Please advise?

**Comment by chulado** [comment]
I know this is an old post, but could someone point me to the name of the file I should edit to set cloudinary to 'true'
