### ISSUE TITLE
Hide a Model

### ISSUE THREAD

**Issue by Globegitter** [keystonejs/keystone-classic#487]
Is it currently possibe to hide a Model from the admin ui? 
I want to have categories for a Post, but I do not want anyone to be able to modify or delete them (they are just getting seeded in at the beginning).

**Comment by carlosalvarez91** [comment]
Is it possible to hide a Parent Model?
Thanks

**Comment by GreenMonkeySaveEarth** [comment]
Looks like `hidden` is no longer supported. 
from `keystone/lib/core/initNav` 
```
if (list.get('hidden')) {
					throw new Error('Invalid Keystone Option (nav): list ' + i + ' is hidden.\n');
				}
```
Is there any update on the `hidden` option?

**Comment by GreenMonkeySaveEarth** [comment]
Hi @JedWatson 
Looks like `hidden` is no longer supported. 
from `keystone/lib/core/initNav` 
```
if (list.get('hidden')) {
    throw new Error('Invalid Keystone Option (nav): list ' + i + ' is hidden.\n');
}
```
Is there any update on the `hidden` option?
