### ISSUE TITLE
Cant upload to s3

### ISSUE THREAD

**Issue by allanhortle** [keystonejs/keystone-classic#532]
Uploading files to s3 causes this error:

```
Error: write EPIPE
  at errnoException (net.js:904:11)
  at Object.afterWrite (net.js:720:19)
```

It's a pretty uninformative error so if you need any other details let me know :)

**Comment by awinecki** [comment]
Hey there, not sure is this is the right issue, however I feel there's still some problem with EU buckets.

I'm running 0.3.2 now, and here's my `fields/types/s3file/S3FileType.js` contents (relevant lines):

```
		console.log(file.mimetype);
267		knox.createClient(field.s3config).putFile(file.path, path + filename, {
			'Content-Type': file.mimetype,
			'x-amz-acl': 'public-read'
		}, function(err, res) {
```

The filetype I'm trying to upload is `video/mp4`. The console.log returns `video/mp4` correctly, however the upload still crashes with `403` response from Amazon.

**Comment by morenoh149** [comment]
@awinecki please read https://github.com/LearnBoost/knox#endpoint and `region`. We are using `putFile` which only seems to work for `US standard`. Could you add support for specifying the region by the developer?

**Comment by yn5** [comment]
Not sure if the issue here but I couldn't use a bucket located in Europe and got the Ireland location (`eu-west-1`) to work by setting the `endpoint` option (described in https://github.com/LearnBoost/knox#endpoint) in Keystone's `'s3 config'`. So my s3 config looks like:
```
's3 config': {
	bucket: <bucket-name>,
	endpoint: 's3-eu-west-1.amazonaws.com',
	key: <bucket-name>,
	secret: <bucket-name>,
},
```

Unfortunately I didn't get it to work for Frankfurt.
