### ISSUE TITLE
Support automatic webP option for cloudinary images

### ISSUE THREAD

**Issue by mbayfield** [keystonejs/keystone-classic#59]
Should be as simple as passing the "f_auto" option when outputing images.

"To leverage this capability, and tell Cloudinary to automatically use WebP when applicable, all you need to do is add 'f_auto' (Format = Auto) to Cloudinary’s smart delivery URLs."

Automatically reduces the file size of images when delivered in Google Chrome browsers.

http://cloudinary.com/blog/transparent_webp_format_cdn_delivery_based_on_visitors_browsers

**Comment by licx** [comment]
@JedWatson how can I use the `f_auto` option?

**Comment by brooksbecton** [comment]
Incase anyone needs it
To use the `f_auto` option you send something like this 

```gql
  image {
    publicUrlTransformed(transformation: { fetch_format: "auto" })
  }
```
