### ISSUE TITLE
Using mongoose plugins doesn't seem to work

### ISSUE THREAD

**Issue by Globegitter** [keystonejs/keystone-classic#590]
I suppose to keep this Issue generic, I don't seem to be able to add mongoose plugins to Keystone.
I thought I could just access `keystone.List('Post').model` to get the native mongoose plugin and therefore specify in my model specification: `Post.model.plugin(...);`

But I am getting the following error:

``` js
TypeError: Object function model(doc, fields, skipId) {
    if (!(this instanceof model))
      return new model(doc, fields, skipId);
    Model.call(this, doc, fields, skipId);
  } has no method 'plugin'
```

Specifically I would love to use the plugin https://github.com/jamescarr/mongoosastic within keystone to provide some powerful search for the frontend.
Unfortunately I don't have any time right now to dig into the issue myself but will try at some point soon. But maybe @JedWatson you know immediately what the issue could be.

**Comment by jeffreypriebe** [comment]
For anyone finding this discussion wanting to setup [mongoosastic](https://github.com/mongoosastic/mongoosastic), the bits are here (add mongoosastic to the schema before register), but to put it in code:

In your model (here named 'Post'):
```
var mongoosastic = require('mongoosastic');

var Post = new keystone.List('Post', ...);

Post.add( {...} );
...
Post.schema.plugin(mongoosastic, { mongoosastic options here, like your host config });
Post.register();
```
More info on [Mongoosastic options](https://www.npmjs.com/package/mongoosastic#setup).

Easy. And agree with @Globegitter, ElasticSearch is awesome. Mongoosastic makes it so easy to get your data indexed.

**Comment by hari419** [comment]
var event = new keystone.List('Event');
event.schema.plugin(timeZone,{ paths: ['event_date'] });
i'm trying to use mongoose timezone plugin but when i'm trying to create a record for events keystone throwing an error 
**Sorry, an error occurred loading the page (500)
Cannot read property 'numAsyncPres' of undefined**
can anyone help me to solve this issue?
