### ISSUE TITLE
less configuration:  doc/code mistmatch

### ISSUE THREAD

**Issue by webteckie** [keystonejs/keystone-classic#666]
The doc for the less option says:  "If you want Keystone to automatically compile .less files into .css files, set this value to the same path as the static option."  However, if you set the static option to an array of paths the less option cannot be set as such.  Not sure if the doc or code should change.  I guess it will depend on whether if the less-middleware doesn't support an array of paths.

**Comment by stunjiturner** [comment]
how do i use 	'less options': 'preprocess.less': {

	}


where of a put the function info?

**Comment by JedWatson** [comment]
@stunjiturner the `less options` setting is an object that is passed directly to `less-middleware`.

so, e.g to use `preprocess.less`:

```
keystone.set('less options', {
  'preprocess.less': function(src, req) {...}
});
```

**Comment by stunjiturner** [comment]
Keystone.set , I understand the configuration file much better now. Can we add use keystone.set() to the docs where it talks about object values for options

Sightuary
