### ISSUE TITLE
Keystone Generator Warning

### ISSUE THREAD

**Issue by cscawley** [keystonejs/keystone-classic#681]
When I run the keystone generator it gives me the following warning at the end of installation. It appears that it's looking for files and some things are undefined, etc., etc. I checked and the packages it's looking for are indeed missing. I simply ran $ npm install after the initial installation and it launches the site just fine. Perhaps the Keystone Generator gets a little bit ahead of itself and starts calling for packages that are not yet installed yet and this kills the process of installing the remaining packages.

> fsevents@0.3.0 install /Users/ccawley/app-dev/keystone/node_modules/nunjucks/node_modules/chokidar/node_modules/fsevents
> node-gyp rebuild

  CXX(target) Release/obj.target/fse/fsevents.o
In file included from ../fsevents.cc:86:
../src/constants.cc:10:66: warning: template argument uses unnamed type
      [-Wunnamed-type-template-args]
  object->Set(NanNewv8::String("kFSEventStreamEventFlagNone"), NanNew<...
                                                                 ^~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/System/Library/Frameworks/CoreServices.framework/Frameworks/CarbonCore.framework/Headers/FSEvents.h:290:1: note: 
      unnamed type used in template argument was declared here
enum {
^
1 warning generated.
  SOLINK_MODULE(target) Release/fse.node
  SOLINK_MODULE(target) Release/fse.node: Finished

> ws@0.4.32 install /Users/ccawley/app-dev/keystone/node_modules/grunt-node-inspector/node_modules/node-inspector/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node
  SOLINK_MODULE(target) Release/bufferutil.node: Finished
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node
  SOLINK_MODULE(target) Release/validation.node: Finished

> kerberos@0.0.4 install /Users/ccawley/app-dev/keystone/node_modules/keystone/node_modules/mongoose/node_modules/mongodb/node_modules/kerberos
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/kerberos/lib/kerberos.o
  CXX(target) Release/obj.target/kerberos/lib/worker.o
  CC(target) Release/obj.target/kerberos/lib/kerberosgss.o
  CC(target) Release/obj.target/kerberos/lib/base64.o
  CXX(target) Release/obj.target/kerberos/lib/kerberos_context.o
  SOLINK_MODULE(target) Release/kerberos.node
  SOLINK_MODULE(target) Release/kerberos.node: Finished

> bson@0.2.15 install /Users/ccawley/app-dev/keystone/node_modules/keystone/node_modules/mongoose/node_modules/mongodb/node_modules/bson
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/bson/ext/bson.o
  SOLINK_MODULE(target) Release/bson.node
  SOLINK_MODULE(target) Release/bson.node: Finished
consolidate@0.10.0 node_modules/consolidate

---

Your KeystoneJS project is ready to go!

For help getting started, visit http://keystonejs.com/guide

To start your new website, run "node keystone".

**Comment by chrisyeung1121** [comment]
nope
