### ISSUE TITLE
Geo tagging in keystone is client side or server side ?

### ISSUE THREAD

**Issue by TejasCMehta** [keystonejs/keystone-classic#690]
I want to enable geotagging in my current project and want to know about how keystone has implemented and also proper approach to implement it.

**Comment by iamjohnlong** [comment]
"When using the UpdateHandler to process changes, you can pass {path}_improve as true to automatically invoke the geolocation."

Do have an example of this @JedWatson ?

**Comment by lazamar** [comment]
Hi @JedWatson, could you provide an example for `googleLookup`. I'm trying to follow the format you outlined above `item._.location.googleLookup` but my location object doesn't have a `googleLookup` function. 
Could you also provide an example for this line, please:
"When using the UpdateHandler to process changes, you can pass {path}_improve as true to automatically invoke the geolocation."

- What does automatically invoke geolocation mean?
- What is the UpdateHandler?
- What is `{path}_improve` ?

Many thanks.
