### ISSUE TITLE
[question] updating models 

### ISSUE THREAD

**Issue by davidchase** [keystonejs/keystone-classic#694]
Hi,
So I see the ability to query, create and delete but nothing about updating... in mongoose we can do `findOneAndUpdate` or just `Model.update`.

So the idea is to have per say a post with title, content, etc and a button when the user clicks the button i want add another content field [textarea] to the current post that they are on and any data they add to the post persist to mongo.

Is this possible?

Thank you

**Comment by eliataylor** [comment]
shailendra735 's is particularly correct for the `Users` model because `user.save()` will re-hash whatever exists on `user.password` (which is pretty rarely the original plain text password when updating).
