### ISSUE TITLE
LocalFiles image path contains 'public'

### ISSUE THREAD

**Issue by davidpaulrosser** [keystonejs/keystone-classic#700]
Hi,

First of all I'd just like to say thanks for an amazing cms : )

After implementing the localFiles field type within my model the images do not correctly show within the admin ui.

The path to the images contains 'public' which obviously can't be accessed frontend.

I've worked about this by adding this line above live 15 in `keystone/templates/localfiles/form.jade`

```
- value.path = value.path.replace('public/', '')
```

Is there a nicer way to solve this?

Thanks,

**Comment by tylkomat** [comment]
On windows the `href` path has backslashes instead of slashes. I tested with `LocalFile`.
```javascript
thumbnail: {
    type: Types.LocalFile,
    dest: baseDir + '/data/thumbnails',
    prefix: '/thumb/',
    allowedTypes: [
        'image/jpeg', 'image/png', 'image/gif', 'image/svg+xml'
    ],
    filename: function(item, file) {
        return item.id + '.' + file.extension;
    },
    format: function(item, file) {
        return '<img src="' + file.href + '" style="max-width: 300px">';
    }
}
```
`{{ item.thumbnail.href }}` for example outputs `\thumb\5542306ff9800d1c23a3cf3b.png`

**Comment by tylkomat** [comment]
This happens because `path.join` creates a platform specific path, but you want to create a URL path, string concatenation should be sufficient.

**Comment by JedWatson** [comment]
Thanks for pointing that out @tylkomat, I've fixed it and will push a new version soon.
