### ISSUE TITLE
KeystoneJS + AngularJS Skeleton

### ISSUE THREAD

**Issue by dvdcastro** [keystonejs/keystone-classic#711]
Hello,

I have created a Skeleton for using [KeystoneJS](http://keystonejs.com) with [AngularJS](https://angularjs.org)

https://github.com/dvdcastro/keystonejs-ng-skeleton

I based it on the yeoman generated project. I've been experimenting with material for angular, but they still have it like in an alpha stage, so the contact form uses bootstrap still. I also tried using a [bootstrap material theme](http://fezvrasta.github.io/bootstrap-material-design/) and it works ok.

If any one has any comments or ideas, let me know.

**Comment by xola139** [comment]
Excellent I test this version, Thanks!
