### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by sebmck** [keystonejs/keystone-classic#744]
# Internationalization

Given that i18n of docs has begun (#720) it's becoming increasingly relevant to include general i18n in keystone. I propose the following API and directory/file structure.
## Importing

In order to import language data into keystone you'd use the following method. Note that keystone would automatically load internal language data:

**keystone.js**

``` javascript
keystone.importLanguage("language");
```
## Structure

The structure of the language data would be a collection of `json` files. They can be a combination of the following two structures:
- `language/LANGUAGE_CODE.json`
- `language/LANGUAGE_CODE/NAMESPACE.json` This can be infinitely nested as the directories will be walked.

For example, the following two files would be equivalent:

**language/en.json**

``` json
{
  "admin": {
    "foo": "bar",
    "bar": "foo"
  }
}
```

**language/en/admin.json**

``` json
{
  "foo": "bar",
  "bar": "foo"
}
```

This allows support for simple and dense language structure. All data would be traversed and an alias key produced that would be a combination of the current key and it's parent namespace joined with something like a dot. For example the previous example would produce the following map:

| Key | Value |
| --- | --- |
| `admin.foo` | `"foo"` |
| `admin.bar` | `"bar"` |
## Formatting

Now there may be a need to include variables in these strings such as titles etc. I propose the following format:

``` json
{
  "foo": "bar $0 $1"
}
```

Where `$x` dictates an index of a value to be included from an input array. Possible additional syntax could be added such as `"bar $,0"` that would automatically humanise numbers from `1000` to `1,000` etc.
## Detection

Browsers send information about the language the users OS is set to via the `Accepts` header. Luckily for us express has a [req.acceptsLanguages](http://expressjs.com/4x/api.html#req.acceptsLanguages) method, this makes automatically selecting a default language trivial.
## Usage

For the following examples the following directory structure is assumed.

**language/en.json**

``` javascript
{
  "user": "User",
  "userTitle": "User: $1",
  "admin": { // Again, this would just be equivalent to having it in the `lang/en/admin.json` file
    "title": "Admin"
  }
}
```
### Backend

``` javascript
keystone.language("en", "user");
keystone.language("en", "user", ["sebmck"]);
keystone.language("en", "admin.title");
```

alternatively it can be accessed from views via just a locals `lang` that's bound to the current users language.
### Frontend

Language data would need to be sent to the users browser. This is where things become _slightly_ more tricky.

This can be achieved pretty easily by just having some connect middleware that'll automatically output it via something like:

``` javascript
app.get("/keystone/language/:code.json", function (req, res) {
  res.json(languageData[req.params.code]);
});
```

It's unneccesary to send **all** language data to the browser, this may be alleviated by providing a way to designate what data **should** be accessible. This may be something as simple as prepending `$` to language keys.
## Conclusion

Would be very interested to hear everyones thoughts. I used this structure when developing [nyx](https://github.com/nyx-platform/nyx) which had pretty [intricate language data](https://github.com/nyx-platform/nyx/blob/master/lib/nyx/core-modules/base/language/en/form.toml).

/cc @JedWatson @gilloud

**Comment by GabrielGil** [comment]
@JedWatson didn't want to show himself about the topic...
