### ISSUE TITLE
Cannot save nested relationship in admin panel

### ISSUE THREAD

**Issue by alexbezhan** [keystonejs/keystone-classic#83]
I have following field in my list:

``` javascript
location: {
    country: { type: Types.Relationship, ref: 'Country' },
    city: { type: Types.Text },
    place: { type: Types.Text }
  }
```

In admin panel when I select country and click save I'm getting following error:
There was an error saving your changes: Cast to ObjectId failed for value "Russia" at path "location.country" (CastError: ObjectId)

If I move country on top level, then it works well.

**Comment by peterhughesdev** [comment]
Apologies for re-opening this if it's been addressed elsewhere - are there any capabilities within Keystone to automate Mongo's schema migration for changes like this?
