### ISSUE TITLE
Exposing forms and DB input to front end users

### ISSUE THREAD

**Issue by robbennet** [keystonejs/keystone-classic#866]
I have a site built on Keystone using HBS templates, I'm curious if there is a suggested method for exposing "keystone editing" functionality to front end users?  Such as registration, login and editing their profile? Any thoughts, suggestions or established methods would be super-helpful.

![screen shot 2015-01-05 at 1 04 26 pm](https://cloud.githubusercontent.com/assets/1012064/5619731/61d8b3fc-94ea-11e4-9fb6-6d759b624071.png)

**Comment by TheDucc** [comment]
Re: In a future version we'll also be making it possible to pull parts of the Admin UI form generation in to the front-end of your site.

Is this a thing yet.  I thought that I read somewhere that something like
  != locals.myModel.fields.myField.form()

would render the input form for myField in myModel.  But I cannot see to get it to work.

**Comment by morenoh149** [comment]
@TheDucc no. The components need to be available under the `public` directory I believe. That move should be done when https://github.com/keystonejs/keystone/issues/957 is done.
