### ISSUE TITLE
Scaffold script for new project structure

### ISSUE THREAD

**Issue by alexander-akait** [keystonejs/keystone-classic#88]
Maybe use create .sh(.bat) files or npm.

**Comment by cleechtech** [comment]
bower with keystone.js. What I have done to add bower after the `yo keystone` command:

```
$ bower init
$ touch .bowerrc
$ rm -rf public/js/bootstrap public/js/jquery  
```

**.bowerrc**
```
{
  "directory": "public/bower_components"
}
```

```
$ bower i jquery bootstrap --save
```

Change **templates/layouts/default.jade** to point to your bower files (bottom of file):

```
script(src='/bower_components/jquery/dist/jquery.min.js')
script(src='/bower_components/bootstrap/dist/bootstrap.min.js')
```

Optional, add `public/bower_components` to **.gitignore**
